"""add auction round calculation fields

Revision ID: 4a3bf2ccd2d6
Revises: 90d74d64d79a
Create Date: 2026-02-02 14:58:38.197693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3bf2ccd2d6'
down_revision: Union[str, Sequence[str], None] = '90d74d64d79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_rounds', sa.Column('is_auto', sa.Boolean(), nullable=True))
    op.add_column('auction_rounds', sa.Column('auto_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_rounds', 'auto_reason')
    op.drop_column('auction_rounds', 'is_auto')
    # ### end Alembic commands ###
