"""add reserve ledger table

Revision ID: 832e5bfabf4b
Revises: 5d606b0bc979
Create Date: 2026-02-03 13:57:28.369203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832e5bfabf4b'
down_revision: Union[str, Sequence[str], None] = '5d606b0bc979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('month_no', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('one_open_auction_per_chit'), table_name='auction_rounds', postgresql_where="((status)::text = 'OPEN'::text)")
    op.alter_column('member_ledger', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_ledger', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('one_open_auction_per_chit'), 'auction_rounds', ['chit_group_id'], unique=True, postgresql_where="((status)::text = 'OPEN'::text)")
    op.drop_table('reserve_ledger')
    # ### end Alembic commands ###
