"""initial clean chitpro schema

Revision ID: 90d74d64d79a
Revises: 
Create Date: 2026-01-26 10:28:44.569913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d74d64d79a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chit_groups', sa.Column('lifecycle_status', sa.String(length=20), nullable=True))
    op.drop_column('chit_groups', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chit_groups', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('chit_groups', 'lifecycle_status')
    # ### end Alembic commands ###
