"""add current_month_no in chit_groups

Revision ID: f85503c73839
Revises: 4a3bf2ccd2d6
Create Date: 2026-02-02 17:42:33.575706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85503c73839'
down_revision: Union[str, Sequence[str], None] = '4a3bf2ccd2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chit_groups', sa.Column('current_month_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chit_groups', 'current_month_no')
    # ### end Alembic commands ###
